export const cars = [
  {
    brand: "Audi",
    model: "A4",
    used: true,
    bodyType: "Sedan",
    drivetrain: "Front-Wheel Drive",
    engine: "2.0L Turbocharged 4-Cylinder",
    transmission: "Automatic",
    horsePower: 248,
    fuelType: "Gasoline",
    exteriorColor: "Black",
    interiorColor: "Black",
  },
  {
    brand: "Audi",
    model: "A5",
    used: false,
    bodyType: "Coupe",
    drivetrain: "All-Wheel Drive",
    engine: "3.0L V6",
    transmission: "Automatic",
    horsePower: 349,
    fuelType: "Gasoline",
    exteriorColor: "White",
    interiorColor: "Black",
  },
  {
    brand: "Audi",
    model: "Q7",
    used: true,
    bodyType: "SUV",
    drivetrain: "All-Wheel Drive",
    engine: "3.0L V6",
    transmission: "Automatic",
    horsePower: 349,
    fuelType: "Diesel",
    exteriorColor: "Black",
    interiorColor: "Beige",
  },
  {
    brand: "Honda",
    model: "Civic",
    used: false,
    bodyType: "Sedan",
    drivetrain: "Front-Wheel Drive",
    engine: "1.5L Turbocharged 4-Cylinder",
    transmission: "Manual",
    horsePower: 174,
    fuelType: "Gasoline",
    exteriorColor: "Red",
    interiorColor: "Black",
  },
  {
    brand: "Honda",
    model: "Accord",
    used: true,
    bodyType: "Sedan",
    drivetrain: "Front-Wheel Drive",
    engine: "2.0L Turbocharged 4-Cylinder",
    transmission: "Automatic",
    horsePower: 252,
    fuelType: "Gasoline",
    exteriorColor: "White",
    interiorColor: "Beige",
  },
  {
    brand: "Toyota",
    model: "Camry",
    used: false,
    bodyType: "Sedan",
    drivetrain: "Front-Wheel Drive",
    engine: "2.5L 4-Cylinder",
    transmission: "Automatic",
    horsePower: 203,
    fuelType: "Gasoline",
    exteriorColor: "Blue",
    interiorColor: "Black",
  },
  {
    brand: "Toyota",
    model: "Corolla",
    used: true,
    bodyType: "Sedan",
    drivetrain: "Front-Wheel Drive",
    engine: "1.8L 4-Cylinder",
    transmission: "Automatic",
    horsePower: 139,
    fuelType: "Gasoline",
    exteriorColor: "Silver",
    interiorColor: "Gray",
  },
  {
    brand: "Subaru",
    model: "Impreza",
    used: false,
    bodyType: "Sedan",
    drivetrain: "All-Wheel Drive",
    engine: "2.0L 4-Cylinder",
    transmission: "Manual",
    horsePower: 152,
    fuelType: "Gasoline",
    exteriorColor: "Gray",
    interiorColor: "Black",
  },
  {
    brand: "Subaru",
    model: "Legacy",
    used: true,
    bodyType: "Sedan",
    drivetrain: "All-Wheel Drive",
    engine: "2.5L 4-Cylinder",
    transmission: "Automatic",
    horsePower: 182,
    fuelType: "Gasoline",
    exteriorColor: "Black",
    interiorColor: "Gray",
  },
  {
    brand: "KIA",
    model: "Optima",
    used: false,
    bodyType: "Sedan",
    drivetrain: "Front-Wheel Drive",
    engine: "2.4L 4-Cylinder",
    transmission: "Automatic",
    horsePower: 185,
    fuelType: "Gasoline",
    exteriorColor: "Black",
    interiorColor: "Beige",
  },
  {
    brand: "Hyundai",
    model: "Sonata",
    used: true,
    bodyType: "Sedan",
    drivetrain: "Front-Wheel Drive",
    engine: "2.5L 4-Cylinder",
    transmission: "Automatic",
    horsePower: 191,
    fuelType: "Gasoline",
    exteriorColor: "White",
    interiorColor: "Beige",
  },
  {
    brand: "Ford",
    model: "Fusion",
    used: false,
    bodyType: "Sedan",
    drivetrain: "Front-Wheel Drive",
    engine: "2.0L Turbocharged 4-Cylinder",
    transmission: "Automatic",
    horsePower: 245,
    fuelType: "Gasoline",
    exteriorColor: "Black",
    interiorColor: "Black",
  },
  {
    brand: "Ford",
    model: "Taurus",
    used: true,
    bodyType: "Sedan",
    drivetrain: "Front-Wheel Drive",
    engine: "3.5L V6",
    transmission: "Automatic",
    horsePower: 288,
    fuelType: "Gasoline",
    exteriorColor: "Silver",
    interiorColor: "Gray",
  },
  {
    brand: "Volvo",
    model: "S60",
    used: false,
    bodyType: "Sedan",
    drivetrain: "Front-Wheel Drive",
    engine: "2.0L Turbocharged 4-Cylinder",
    transmission: "Automatic",
    horsePower: 250,
    fuelType: "Gasoline",
    exteriorColor: "Red",
    interiorColor: "Black",
  },
  {
    brand: "Volvo",
    model: "S90",
    used: true,
    bodyType: "Sedan",
    drivetrain: "All-Wheel Drive",
    engine: "2.0L Turbocharged 4-Cylinder",
    transmission: "Automatic",
    horsePower: 250,
    fuelType: "Gasoline",
    exteriorColor: "Blue",
    interiorColor: "Beige",
  },
];
